# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Open Actuarial Analysis'
tagline:          'Using open source tools and actuarial science'
description:      'You got the science, you got the open tools'
url:              'http://pirategrunt.github.io/OpenActuarialAnalysis'
baseurl:          'http://pirategrunt.github.io/OpenActuarialAnalysis'

# Navigation
navigation:
- text: About
  url: /about/
- text: Data
  url: /data/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/

# Author Details
author:         'Brian A. Fannin'
linkedin:       'https://ae.linkedin.com/in/olakara/'
twitter:        'https://twitter.com/FanninQED'
facebook:       'https://www.facebook.com/olakara'

# Google Analytics
gahandler: 'UA-52149651-1'

# Disqus
disqushandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.1.1
